import type {
    DashboardProject,
    DashboardFilters,
} from "./dashboard.types";

export const reportingPeriods = [
    "April 2026",
    "March 2026",
    "February 2026",
    "January 2026",
];

export const ministries = [
    "All Ministries",
    "Road Transport",
    "Railways",
    "Power",
    "Water Resources",
    "Housing & Urban Affairs",
    "Coal",
    "Steel",
];

export const sectors = [
    "All Sectors",
    "Transport & Logistics",
    "Energy",
    "Water & Sanitation",
    "Social Infrastructure",
    "Coal",
    "Steel",
    "Mining",
];

export const states = [
    "All States",
    "Gujarat",
    "Maharashtra",
    "Rajasthan",
    "Karnataka",
    "Uttar Pradesh",
    "Madhya Pradesh",
    "Tamil Nadu",
];

export const riskLevels = [
    "All Risk Levels",
    "Critical",
    "High",
    "Elevated",
    "Moderate",
    "Low",
];

export const statuses = [
    "All Statuses",
    "Ongoing",
    "Delayed",
    "Completed",
];

export const defaultDashboardFilters: DashboardFilters = {
    period: "April 2026",
    ministry: "All Ministries",
    sector: "All Sectors",
    state: "All States",
    risk: "All Risk Levels",
    status: "All Statuses",
};

export const dashboardProjects: DashboardProject[] = [
    {
        id: "PM-400005",
        name: "National Highway Development",
        ministry: "Road Transport",
        sector: "Transport & Logistics",
        state: "Gujarat",
        originalCost: 3200,
        revisedCost: 3850,
        riskScore: 89,
        costRisk: "High",
        delayRisk: "Critical",
        delayMonths: 14,
        physicalProgress: 41,
        status: "Delayed",
    },
    {
        id: "PM-400117",
        name: "Regional Water Supply System",
        ministry: "Water Resources",
        sector: "Water & Sanitation",
        state: "Maharashtra",
        originalCost: 1840,
        revisedCost: 2260,
        riskScore: 82,
        costRisk: "High",
        delayRisk: "High",
        delayMonths: 11,
        physicalProgress: 54,
        status: "Delayed",
    },
    {
        id: "PM-400221",
        name: "Power Transmission Expansion",
        ministry: "Power",
        sector: "Energy",
        state: "Rajasthan",
        originalCost: 4100,
        revisedCost: 4680,
        riskScore: 78,
        costRisk: "High",
        delayRisk: "High",
        delayMonths: 8,
        physicalProgress: 63,
        status: "Ongoing",
    },
    {
        id: "PM-400331",
        name: "Integrated Railway Corridor",
        ministry: "Railways",
        sector: "Transport & Logistics",
        state: "Karnataka",
        originalCost: 5100,
        revisedCost: 5540,
        riskScore: 74,
        costRisk: "Elevated",
        delayRisk: "High",
        delayMonths: 6,
        physicalProgress: 71,
        status: "Ongoing",
    },
    {
        id: "PM-400442",
        name: "Urban Infrastructure Expansion",
        ministry: "Housing & Urban Affairs",
        sector: "Social Infrastructure",
        state: "Tamil Nadu",
        originalCost: 2200,
        revisedCost: 2360,
        riskScore: 67,
        costRisk: "Elevated",
        delayRisk: "Elevated",
        delayMonths: 4,
        physicalProgress: 76,
        status: "Ongoing",
    },
    {
        id: "PM-400551",
        name: "Coal Handling Modernisation",
        ministry: "Coal",
        sector: "Coal",
        state: "Madhya Pradesh",
        originalCost: 1600,
        revisedCost: 1690,
        riskScore: 58,
        costRisk: "Moderate",
        delayRisk: "Moderate",
        delayMonths: 3,
        physicalProgress: 81,
        status: "Ongoing",
    },
    {
        id: "PM-400661",
        name: "Steel Plant Expansion",
        ministry: "Steel",
        sector: "Steel",
        state: "Odisha",
        originalCost: 4700,
        revisedCost: 4900,
        riskScore: 49,
        costRisk: "Moderate",
        delayRisk: "Moderate",
        delayMonths: 2,
        physicalProgress: 86,
        status: "Ongoing",
    },
    {
        id: "PM-400771",
        name: "National Water Grid",
        ministry: "Water Resources",
        sector: "Water & Sanitation",
        state: "Uttar Pradesh",
        originalCost: 2900,
        revisedCost: 2980,
        riskScore: 38,
        costRisk: "Low",
        delayRisk: "Moderate",
        delayMonths: 1,
        physicalProgress: 92,
        status: "Ongoing",
    },
    {
        id: "PM-400882",
        name: "Freight Logistics Corridor",
        ministry: "Railways",
        sector: "Transport & Logistics",
        state: "Maharashtra",
        originalCost: 6200,
        revisedCost: 7000,
        riskScore: 87,
        costRisk: "High",
        delayRisk: "Critical",
        delayMonths: 13,
        physicalProgress: 46,
        status: "Delayed",
    },
    {
        id: "PM-400993",
        name: "Regional Power Infrastructure",
        ministry: "Power",
        sector: "Energy",
        state: "Gujarat",
        originalCost: 2500,
        revisedCost: 2730,
        riskScore: 72,
        costRisk: "Elevated",
        delayRisk: "High",
        delayMonths: 7,
        physicalProgress: 61,
        status: "Delayed",
    },
    {
        id: "PM-401104",
        name: "Metro Connectivity Programme",
        ministry: "Housing & Urban Affairs",
        sector: "Social Infrastructure",
        state: "Karnataka",
        originalCost: 3400,
        revisedCost: 3690,
        riskScore: 63,
        costRisk: "Elevated",
        delayRisk: "Elevated",
        delayMonths: 4,
        physicalProgress: 73,
        status: "Ongoing",
    },
    {
        id: "PM-401215",
        name: "Integrated Mining Infrastructure",
        ministry: "Mining",
        sector: "Mining",
        state: "Rajasthan",
        originalCost: 1850,
        revisedCost: 1975,
        riskScore: 52,
        costRisk: "Moderate",
        delayRisk: "Moderate",
        delayMonths: 3,
        physicalProgress: 79,
        status: "Ongoing",
    },
];

export const monthlyPortfolioData = [
    {
        month: "Jan",
        projects: 1884,
        highRisk: 151,
        delayed: 391,
    },
    {
        month: "Feb",
        projects: 1907,
        highRisk: 162,
        delayed: 402,
    },
    {
        month: "Mar",
        projects: 1944,
        highRisk: 176,
        delayed: 416,
    },
    {
        month: "Apr",
        projects: 1981,
        highRisk: 184,
        delayed: 427,
    },
];