"""create PAIMANA initial schema

Revision ID: 3c0896ff47f2
Revises: 
Create Date: 2026-09-01 01:44:56.197329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0896ff47f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=True),
    sa.Column('ministry', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('implementing_agency', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('original_cost_cr', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('revised_cost_cr', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('expenditure_cr', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('original_end_date', sa.Date(), nullable=True),
    sa.Column('revised_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_ministry'), ['ministry'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_code'), ['project_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_year', sa.Integer(), nullable=True),
    sa.Column('snapshot_month', sa.Integer(), nullable=True),
    sa.Column('predicted_cost_overrun_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('future_delay_probability', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('future_progress_stall_probability', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('cost_risk_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('overall_risk_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('early_warning_active', sa.Boolean(), nullable=False),
    sa.Column('early_warning_priority', sa.String(length=30), nullable=False),
    sa.Column('early_warning_reasons', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_early_warning_active'), ['early_warning_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_risk_level'), ['risk_level'], unique=False)

    op.create_table('project_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_year', sa.Integer(), nullable=False),
    sa.Column('snapshot_month', sa.Integer(), nullable=False),
    sa.Column('original_cost_cr', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('revised_cost_cr', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('expenditure_cr', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('physical_progress_pct', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.Column('cost_overrun_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('schedule_change_days', sa.Integer(), nullable=True),
    sa.Column('expenditure_change_cr_paimana', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('expenditure_change_cr_flash', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('progress_change_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('flash_history_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'snapshot_year', 'snapshot_month', name='uq_project_snapshot')
    )
    with op.batch_alter_table('project_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_snapshots_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_snapshots_snapshot_year'), ['snapshot_year'], unique=False)

    op.create_table('early_warnings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=True),
    sa.Column('warning_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('early_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_early_warnings_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_early_warnings_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_early_warnings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_early_warnings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('early_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_early_warnings_status'))
        batch_op.drop_index(batch_op.f('ix_early_warnings_project_id'))
        batch_op.drop_index(batch_op.f('ix_early_warnings_priority'))
        batch_op.drop_index(batch_op.f('ix_early_warnings_prediction_id'))

    op.drop_table('early_warnings')
    with op.batch_alter_table('project_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_snapshots_snapshot_year'))
        batch_op.drop_index(batch_op.f('ix_project_snapshots_project_id'))

    op.drop_table('project_snapshots')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_risk_level'))
        batch_op.drop_index(batch_op.f('ix_predictions_project_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_early_warning_active'))

    op.drop_table('predictions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_state'))
        batch_op.drop_index(batch_op.f('ix_projects_sector'))
        batch_op.drop_index(batch_op.f('ix_projects_project_code'))
        batch_op.drop_index(batch_op.f('ix_projects_ministry'))

    op.drop_table('projects')
    # ### end Alembic commands ###
